@baseUrl = http://localhost:8080/api
@correoCliente = cliente@test.com
@contrasenaCliente = 123456

###
# @capture usuarioId=id
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "correo": "{{correoCliente}}",
  "contrasena": "{{contrasenaCliente}}",
  "nombre": "Juan",
  "apellido": "Perez",
  "telefono": "999888777",
  "direccion": "Av. Lima 123",
  "rol": "CLIENTE"
}

###
# @capture token=token
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "correo": "{{correoCliente}}",
  "contrasena": "{{contrasenaCliente}}"
}