@baseUrl = http://localhost:8080/api
@token =
@usuarioId =

###
GET {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}
