@baseUrl = http://localhost:8080/api
@token =
@usuarioId =
@carritoId =

###
# @capture carritoId=id
GET {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}
