@baseUrl = http://localhost:8080/api
@token = PEGAR_TOKEN_DEL_LOGIN
@usuarioId = PEGAR_UUID_DEL_USUARIO

###
GET {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}

###
DELETE {{baseUrl}}/api/carritos/usuario/{{usuarioId}}
Authorization: Bearer {{token}}
