@baseUrl = http://localhost:8080/api
@carritoId =
@itemId =
@productoId =

###
# @capture itemId=id
POST {{baseUrl}}/api/carritos/{{carritoId}}/items
Content-Type: application/json

{
  "productoId": "{{productoId}}",
  "cantidad": 2
}

###
GET {{baseUrl}}/api/carritos/{{carritoId}}/items

###
PUT {{baseUrl}}/api/carritos/{{carritoId}}/items/{{itemId}}
Content-Type: application/json

{
  "cantidad": 5
}

###
DELETE {{baseUrl}}/api/carritos/{{carritoId}}/items/{{itemId}}
