@baseUrl = http://localhost:8080/api
@marcaId =

###
# @capture marcaId=id
POST {{baseUrl}}/api/marcas-vehiculos
Content-Type: application/json

{
  "nombre": "{{nombreMarca}}",
  "paisOrigen": "Japon",
  "activo": true
}

###
GET {{baseUrl}}/api/marcas-vehiculos

###
GET {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}

###
PUT {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}
Content-Type: application/json

{
  "nombre": "{{nombreMarca}}",
  "paisOrigen": "Japon",
  "activo": true
}

###
PATCH {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}/toggle-activo

###
DELETE {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}