@baseUrl = http://localhost:8080/api
@marcaId =

###
GET {{baseUrl}}/api/marcas-vehiculos

###
GET {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}

###
POST {{baseUrl}}/api/marcas-vehiculos
Content-Type: application/json

{
  "nombre": "Toyota",
  "paisOrigen": "Japón",
  "activo": true
}

###
PUT {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}
Content-Type: application/json

{
  "nombre": "Toyota",
  "paisOrigen": "Japón",
  "activo": true
}

###
PATCH {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}/toggle-activo

###
DELETE {{baseUrl}}/api/marcas-vehiculos/{{marcaId}}
