@baseUrl = http://localhost:8080/api
@modeloId =
@marcaId =

###
# @capture modeloId=id
POST {{baseUrl}}/api/modelos-vehiculos
Content-Type: application/json

{
  "nombre": "{{nombreModelo}}",
  "marcaId": "{{marcaId}}",
  "tipoVehiculo": "Sedan",
  "activo": true
}

###
GET {{baseUrl}}/api/modelos-vehiculos

###
GET {{baseUrl}}/api/modelos-vehiculos/marca/{{marcaId}}

###
GET {{baseUrl}}/api/modelos-vehiculos/{{modeloId}}

###
PUT {{baseUrl}}/api/modelos-vehiculos/{{modeloId}}
Content-Type: application/json

{
  "nombre": "{{nombreModelo}}",
  "marcaId": "{{marcaId}}",
  "tipoVehiculo": "Sedan",
  "activo": true
}

###
PATCH {{baseUrl}}/api/modelos-vehiculos/{{modeloId}}/toggle-activo

###
DELETE {{baseUrl}}/api/modelos-vehiculos/{{modeloId}}