@baseUrl = http://localhost:8080/api
@stockId =
@productoId =

###
GET {{baseUrl}}/api/stocks

###
# @capture stockId=id
GET {{baseUrl}}/api/stocks/producto/{{productoId}}

###
GET {{baseUrl}}/api/stocks/{{stockId}}

###
GET {{baseUrl}}/api/stocks/bajo-stock

###
PUT {{baseUrl}}/api/stocks/producto/{{productoId}}
Content-Type: application/json

{
  "stockMinimo": 10,
  "ubicacionAlmacen": "B-02"
}
