@baseUrl = http://localhost:8080/api
@usuarioId =
@empleadoId =
@correoEmpleado = empleado@test.com
@contrasenaActual = 123456
@contrasenaNueva = 654321

###
GET {{baseUrl}}/api/usuarios

###
GET {{baseUrl}}/api/usuarios/{{usuarioId}}

###
# @capture empleadoId=id
POST {{baseUrl}}/api/usuarios
Content-Type: application/json

{
  "correo": "{{correoEmpleado}}",
  "contrasena": "123456",
  "nombre": "Ana",
  "apellido": "Gomez",
  "telefono": "999111222",
  "direccion": "Av. Brasil 456",
  "rol": "EMPLEADO"
}

###
PATCH {{baseUrl}}/api/usuarios/{{empleadoId}}/password
Content-Type: application/json

{
  "contrasenaActual": "{{contrasenaActual}}",
  "contrasenaNueva": "{{contrasenaNueva}}"
}

###
PATCH {{baseUrl}}/api/usuarios/{{empleadoId}}/toggle-activo

###
DELETE {{baseUrl}}/api/usuarios/{{empleadoId}}
