server.port=8080
server.servlet.context-path=/api

spring.application.name=autopartes-backend
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.ruvuaponemmepdwnqfce.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=o1s2w3q4@AAA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway - desactivado temporalmente (PostgreSQL 17 no soportado por Flyway actual)
spring.flyway.enabled=false

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.currency.code=PEN
app.currency.symbol=S/.
app.upload.dir=uploads